export interface FormValuesInterface {
  nombre?: string,
  ciudad?: string,
  delegacion?: string,
  colonia?: string,
  movil?: string,
  fijo?: string,
  correo?: string,
  t_examen?: string,
  enterado?: string,
  campaña?: string,
  agente?: string,
  seguimiento?: string,
  comen?: string,
}